'use strict';

const express = require('express');
const {
  createIntent,
  verifyPayment,
  capturePayment,
} = require('../controllers/payments.controller');
const {
  renderJazzcashCheckout,
  handleJazzcashReturn,
} = require('../controllers/jazzcash-checkout.controller');
const { requireStaff } = require('../lib/require-staff');

const router = express.Router();

router.get('/checkout/jazzcash/return', handleJazzcashReturn);
router.post('/checkout/jazzcash/return', express.urlencoded({ extended: true }), handleJazzcashReturn);
router.get('/checkout/jazzcash/:txnRefNo', renderJazzcashCheckout);

router.get('/checkout/:gateway/:token', (req, res) => {
  const { gateway, token } = req.params;
  if (gateway === 'jazzcash') {
    return res.redirect(307, `/payments/checkout/jazzcash/${encodeURIComponent(token)}`);
  }
  const escapeHtml = (value) => String(value).replace(/[&<>"']/g, (c) => `&#${c.charCodeAt(0)};`);
  res.status(200).send(
    `<!doctype html><html><head><meta charset="utf-8"><title>Payment Checkout</title></head><body style="font-family:system-ui,sans-serif;padding:24px;"><h2>Payment Checkout Stub</h2><p>Gateway: <strong>${escapeHtml(gateway)}</strong></p><p>Token: <code>${escapeHtml(token)}</code></p><p>This URL is generated by the payment service and can be replaced with real gateway checkout/redirection logic.</p></body></html>`
  );
});

// Called by the POS; the checkout/return routes above are for customers and gateways.
router.post('/create-intent', requireStaff, createIntent);
router.post('/verify', requireStaff, verifyPayment);
router.post('/capture', requireStaff, capturePayment);

module.exports = router;
